# docker-compose.yml
version: '3.7' # Specify version of Docker Compose

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000